config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get "home/index"
   # root "home#index"
   root "friends#index"
   get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this Friend!" if @friend.nil? 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"John" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Doe" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class:"form-label" %>
    <%= form.text_field :email, class:"form-control", placeholder:"johndoe@example.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block", class:"form-label" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"123 456 7890" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, style: "display: block", class:"form-label" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"@johndoesstuff" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mb-1">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="p-3 bg-body-secondary">
  <h1 class="display-4">
    <%= friend.first_name %> <%= friend.last_name %>
  </h1>
  <p class="lead">
    <%= friend.email %> | <%= friend.phone %> | <%= friend.twitter %>
  </p>
  <hr class="my-4">
</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1 class="display-4">Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div class="d-flex flex-row mb-3">
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary me-2" %>
  <%= button_to 'Delete', @friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger me-2" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark me-2" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <% content_for :title, "Friends" %>

  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>  

    <tbody>
      <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
        <tr>
          <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

<% else %>
  <h1 class="display-4">Welcome to Friends App!</h1>
  <p>Please Login to continue.</p>
<% end %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<div class="card mb-3">
  <h4 class="card-header">Add New friend</h4>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div class="p-3 bg-body-secondary d-flex justify-content-between">
  <div>
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"p-2 mb-2 btn btn-secondary" %>
    <%= link_to "Back to friends", friends_path, class:"p-2 mb-2 btn btn-dark" %>
  </div>
  <%= button_to "Delete this friend", @friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
  	<%= link_to "Friends", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About us", home_about_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1 class="display-4">About Us!</h1>

app/views/home/index.html.erb
<h1 class="display-4">Hello World!</h1>
This is my first Rails webpage

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for(:title) || "Friends" %></title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">

      <br>
      <% if(notice) %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>      
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>